### ISSUE TITLE
Remove that music

### ISSUE THREAD

**Issue by techguy16** [Endermanch/XPKeygen#1]
Sorry - you may like the music, but when I launched the program, that `pxiii.wav` track got really annoying and I could not focus on generating the product key. Can this music be removed?

**Comment by xplanthris** [comment]
Just turn off your speakers

**Comment by techguy16** [comment]
No, I won't turn off my speakers - I was on a Google Meet.
Can there be at least an option to turn it off?

**Comment by HolyNetworkAdapter** [comment]
rebuild without the music then?

**Comment by techguy16** [comment]
I use Linux & Wine, MonoDevelop doesn't work, and I can't install Visual Studio (tried 2012)

**Comment by xplanthris** [comment]
> No, I won't turn off my speakers - I was on a Google Meet. Can there be at least an option to turn it off?

I mean who generates windows xp keys during a meeting but I'll try to build it without music for you

**Comment by techguy16** [comment]
Just delete `pxiii.wav` from the resources folder and remove any references. (from what I know)

**Comment by xplanthris** [comment]
> Just delete `pxiii.wav` from the resources folder and remove any references. (from what I know)

You'd still need to build it

**Comment by Endermanch** [comment]
**Added the option to stop the music in v2.2**.
The music will still autoplay by default.

**Comment by techguy16** [comment]
@Endermanch thanks (from a viewer of your channel :smiley:)
