### ISSUE TITLE
Possible False Positive On "Keygen.exe"

### ISSUE THREAD

**Issue by TrialMedusa64** [Endermanch/XPKeygen#13]
Recently I Ran Your Keygen Through VirusTotal, And Because Its Obviously A **Keygen**, Of Course Its Gonna Be Detect It As "Malware" Even Though, Its **Malware-Free.**

Just Want To Bring This Up To Everyone Who Are Sus About It.

Link: [https://www.virustotal.com/gui/file/c91b157d9de28b75f490883ca71a496f77d8ff2571da665e31e734a07966ab13/detection](url)

Image:
![Screenshot 2023-06-07 085009](https://github.com/Endermanch/XPKeygen/assets/123215941/df9597b7-dd03-4ac2-9b28-504061c4a2d0)

**Comment by TrialMedusa64** [comment]
Odd! usually keygens are detected as "HackTool/Keygen" I might be remembering it wrong. anyway thanks for telling me

**Comment by Bang1338** [comment]
there's no way to get around unless the keygen protected very hard

**Comment by TrialMedusa64** [comment]
let tell you a secret: my avatar is a **Identicon!**

**Comment by TrialMedusa64** [comment]
anyway so that would explain it! i wanna say thank you to everyone for your helping
