### ISSUE TITLE
Complete Malware

### ISSUE THREAD

**Issue by lolt656** [Endermanch/XPKeygen#17]
Remove this from github...
Virus Total says RANSOMEWARE.ROYAL

**Comment by lolt656** [comment]
![FzeGFFxWAAM0iOW](https://github.com/Endermanch/XPKeygen/assets/114013207/81f305b7-6b25-4bc4-a17b-0bcaa5beef30)

**Comment by thepwrtank18** [comment]
Keygens are automatically said to be malware, since why would Microsoft let you download something that potentially loses a customer from them?

You can view the source code right here and see that it's not a virus.

**Comment by lolt656** [comment]
well its called Buy Legit Keys not Fake Activators that wont do anything...

**Comment by thepwrtank18** [comment]
![image](https://github.com/Endermanch/XPKeygen/assets/57580668/dde7ccd5-a5ad-48b6-ae6c-46f9fefaf4e7)

**Comment by thepwrtank18** [comment]
1. Legit keys are becoming harder and harder to come by.
2. XPKeygen isn't an activator, we don't make "fake activators", or activators at all for that matter.

**Comment by Neo-Desktop** [comment]
> New Account
> First issue
> Complete Malware
> Shills some random site that's more likely to give you malware

I'll have what he's having because no one sober has that amount of audacity

**Comment by thepwrtank18** [comment]
shit, it's worse than a 9 year old, it's a scam bot

**Comment by thepwrtank18** [comment]
![image](https://github.com/Endermanch/XPKeygen/assets/57580668/95e8470d-ed9b-444d-9d8d-c52251c67655)

**Comment by techguy16** [comment]
**Microsoft's world**:
Keygen = malware

**Others**:
Keygen = fun
