### ISSUE TITLE
Avast Free quarantines XPKeygen.exe

### ISSUE THREAD

**Issue by Salk73** [Endermanch/XPKeygen#18]
Hello!

I wanted to report that my antivirus automatically puts the .exe file (v2.7) in quarantine informing that the file is infected with a trojan called _MalwareX-gen_.

Very possibly a falsa alarm, but I thought I'd mention it here.

**Comment by thepwrtank18** [comment]
Keygens are commonly detected as malware since AV companies detect pirated programs/tools to pirate programs as malware.

**Comment by Salk73** [comment]
Okay.

Thanks!
