### ISSUE TITLE
Help with OEM copy of XP (if possible)

### ISSUE THREAD

**Issue by Ximerixx** [Endermanch/XPKeygen#21]
It seems (as i saw images of disks on the internet) i have a OEM version of XP
and I really want tot calculate a Product Key for it  :0

welp this keygen makes VLK keys, (that disks was used to distribute in volume as name says) and as none of the keys i generated didn't work, i've decided to look up whole readme, Knowledge base, etc.
I am inclined to the fact that I do not have a VLK version of the product, but something else.

Now the questions i have about whole thing:
1. I want for sure what kind of disk i have. It seems its OEM cuz it says "distributed only with new equipment" on Russian and label "Service pack 2 (SP2) 2002 version". 
CD on windows says some gibberish, it hints about some kind of oem thing "VX2POEM_RU" 
2. If it isn't possible to use current version of XPKeygen, how i can do that by hands? I meant what should i do next after getting hands on pidgen.dll of that particular cd? 

I hope someone will help me with that, I just want to do out of curiosity and find the reason why this isn't working. :P

**Comment by thepwrtank18** [comment]
Use [UMSKT](https://github.com/umskt/umskt) for further product support.

**Comment by Ximerixx** [comment]
> 

Well yes, of course...
But there's no any template(?) for such OEM product...
Or (very likely) me too dumbo for that

**Comment by WitherOrNot** [comment]
If you still need help with this, download UMSKT from here:

https://github.com/UMSKT/UMSKT/actions/runs/5497710500

Extract umskt.exe to a folder, then open Command Prompt and run `cd <folder where umskt is>`.

From [this page](https://www.angelfire.com/comics/observer/wxpvol.htm) it seems you have Professional SP2b OEM, so try running this:

`umskt -b 2D -c 400`

Please let me know if the key generated from this command doesn't work.

**Comment by Ximerixx** [comment]
> If you still need help with this, download UMSKT from here (downloads under the Artifacts section):
> 
Thank you very much, I will try it tomorrow for sure.

**Comment by Ximerixx** [comment]
Well, tried it a couple of times and it didn't work (

**Comment by Ximerixx** [comment]
I found SETUPP.ini
it has following content, can i use it to genereate keys?
[Pid]
ExtraData=786F687170637175716954806365EF
Pid=76456OEM

**Comment by WitherOrNot** [comment]
You can also upload just PIDGEN.DLL and DPCDLL.DLL, on the disk these files may have a .DL_ extension.

**Comment by Ximerixx** [comment]
I uploaded only those DLLs
here: https://pixeldrain.com/u/iq1Rj4CD

//for some reason github won't let me upload 7z lol

**Comment by WitherOrNot** [comment]
Try `umskt -b 33 -c 400`.

**Comment by Ximerixx** [comment]
> umskt -b 33 -c 400
That worked first try!

i think my disk differs for some reason, maybe because it's a 2002 version?

If it is, please add vaules to keys.json as 2002 SP2 in UMSKT

**Comment by Ximerixx** [comment]
![изображение](https://github.com/Endermanch/XPKeygen/assets/94797169/d3277e84-2e67-4f5e-8afc-5daed69d5f91)
Yup, that's professional

IDK why -b 33 worked, it's for starter edition, isn't it?

**Comment by Ximerixx** [comment]
i can send an ISO if that's something intresting

**Comment by WitherOrNot** [comment]
Please share if you can! I am also curious about this discrepancy. It wouldn't be the first time that different products share the same BINK ID, but most SPs share BINKs with the RTM edition.

**Comment by Ximerixx** [comment]
How i can upload a 7z archive?
it's about 550 MB in 7z

**Comment by WitherOrNot** [comment]
you can use pixeldrain

**Comment by Ximerixx** [comment]
There ya go: https://pixeldrain.com/u/gBAiNn8K

I think that CD was licensed for internal use in some company, that's why it differs

**Comment by WitherOrNot** [comment]
Thanks! I also located an English copy of this version for comparison.

**Comment by WitherOrNot** [comment]
You can close this issue, since you have the activation parameters.

**Comment by Ximerixx** [comment]
> You can close this issue, since you have the activation parameters.

Sure, if you find something interesting, make an issue on any my repo
I really would like to investigate that iso with ya)
