### ISSUE TITLE
Insight on the malware.

### ISSUE THREAD

**Issue by rfl890** [Endermanch/XPKeygen#27]
I've got a CLI version of this tool up and running with windows defender, no flag. Maybe it's Win32 UI that defender is flagging.

**Comment by WitherOrNot** [comment]
Most likely it's just because you changed the contents significantly. MS Defender flags anything that acts as a "crack tool", even if it's for abandonware.

**Comment by rfl890** [comment]
That's probably it. Some guy ported this to the browser with WASM, imo it's the most widely-available way to get the functionality of this tool. 
[https://mskt.surge.sh/](https://mskt.surge.sh/)
