### ISSUE TITLE
How are windows 2000 product keys generated and verified

### ISSUE THREAD

**Issue by Jwaliczek8888** [Endermanch/XPKeygen#33]
It would be pretty useful to know how windows 2000 keys are generated and verified because I’m trying to create a keygen that only I will use

**Comment by moxie-coder** [comment]
you got the source code for this

**Comment by moxie-coder** [comment]
🤷‍♂️

**Comment by Jwaliczek8888** [comment]
Huh? Where

**Comment by thepwrtank18** [comment]
https://github.com/UMSKT/UMSKT
