### ISSUE TITLE
random...

### ISSUE THREAD

**Issue by CPScript** [Endermanch/XPKeygen#4]
Damn, I wish you would test some of my programs, but I doubt that most of them would work...🫠

Also I love the YT content... 💯 💯 💯

**Comment by techguy16** [comment]
You know that @Endermanch doesn't test malware on demand.

**Comment by CPScript** [comment]
I know, and I wasn't demanding it...

**Comment by halal-beef** [comment]
Is it really necessary to open a misc gh issue on a completely unrelated project, you could've emailed him or something

**Comment by techguy16** [comment]
Comment on https://github.com/Endermanch/MalwareDatabase or email @Endermanch at realendermanch@gmail.com instead.
