### ISSUE TITLE
Python Library?

### ISSUE THREAD

**Issue by techguy16** [Endermanch/XPKeygen#5]
@Endermanch,
I was just wondering if you could write this in Python and submit a PR on my [keygenlib repository](https://github.com/techguy16/keygenlib) (I've been trying to write it in Python, but I can't figure it out, nor can ChatGPT 'of all things').
@techguy16 😃

**Comment by iPedroLB** [comment]
The original code is at TheMCHK/WindowsXPKg (the same code with proper instructions is on my profile)
Reimplement it yourself ;)

**Comment by iPedroLB** [comment]
Original code by z22 is what i mean
Andrew just rewrote it and made a GUI and some other improvements

**Comment by Endermanch** [comment]
> The original code is at TheMCHK/WindowsXPKg (the same code with proper instructions is on my profile) Reimplement it yourself ;)

That's not the original. The original was uploaded onto PlanetWPA by z22.

**Comment by techguy16** [comment]
@iPedroLB I know you've rewritten it, I saw that while I was searching.

**Comment by techguy16** [comment]
@iPedroLB I have tried, with only a Product ID generator working.
```python
import string
import random
import math
import struct
import hashlib
from win95 import KeyGenerator

def getSum(n):
    sum = 0
    for digit in str(n): 
      sum += int(digit)      
    return sum

def is_whole(n):
    return n % 1 == 0

def convertTuple(tup):
        # initialize an empty string
    str = ''
    for item in tup:
        str = str + item
    return str
    
key1 = KeyGenerator.retailkey()

key2 = key1[4:10]

key3 = getSum(key2)

key4 = key3 / 7

decimal = True
while decimal:
    if is_whole(key4) == 0:
        key1 = KeyGenerator.retailkey()
        key2 = key1[4:10]
        key3 = getSum(int(key2))
        key4 = key3 / 7
        decimal = True
    else:
        print("RAW KEY: ", key1)
        print("Part we're focusing on: ", key2)
        print("Sum of second part: ", key3)
        print("What second part sum divided by 7 equals: ", key4)
        key5 = "640" + key1[3:10] + str(math.trunc(key4))
        print("Plus check digit: ", key5)
        decimal = False
        break
        
random3 = random.randint(1, 999)
random4 = str(random3)
key6 = "PPPPP-", str(key5), "-23", random4.zfill(3)
key7 = convertTuple(key6)
print("\nProduct ID: " + key7)
```

**Comment by techguy16** [comment]
Heya, I've got a WinXP VLK keygen partially working, but only 1 in 20 keys are valid. I suppose I'll keep posting updates here if you're interested
